# Uncomment the next line to define a global platform for your project
platform :osx, '12.0'

target 'ICUdep' do
  use_frameworks!
  pod 'icu4c-iosx', :git => 'https://github.com/apotocki/icu4c-iosx'
end
